services:
  alloy:
    image: grafana/alloy:v1.11.3
    container_name: alloy
    restart: unless-stopped
    volumes:
      - ./monitoring/config.alloy:/etc/alloy/config.alloy:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy
    environment:
      - ALLOY_LOG_LEVEL=info
    depends_on:
      - tempo
      - loki
    ports:
      - "4317"
      - "4318"
      - "12345"
      - "12347"
    networks:
      - dokploy-network

  tempo:
    image: grafana/tempo:2.9.0
    container_name: tempo
    restart: unless-stopped
    volumes:
      - ./monitoring/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo-data:/var/tempo
    command:
      - -config.file=/etc/tempo/tempo.yaml
    networks:
      - dokploy-network

  loki:
    image: grafana/loki:3.5.8
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./monitoring/loki.yaml:/etc/loki/loki.yaml:ro
      - loki-data:/loki
    command:
      - -config.file=/etc/loki/loki.yaml
    networks:
      - dokploy-network

  grafana:
    image: grafana/grafana:12.2.1
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./monitoring/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles
      - GF_AUTH_ANONYMOUS_ENABLED=false
      # username: admin
      # initPassword: admin
      # updatedPassword: Qwerty@123
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_PLUGINS_ENABLE_ALPHA=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=false
    depends_on:
      - tempo
      - loki
    ports:
      - "3000"
    networks:
      - dokploy-network

volumes:
  tempo-data:
  loki-data:
  grafana-data:

networks:
  dokploy-network:
    external: true
